Some changes.
EVasseure/cprint pull request #3
Opened 2021-01-03 17:20 UTC by TheTechRobo

- Formatting and grammar in the README file.
- Add colorama package suggestion on Windows to the README.md.
- Add support for choosing the fatal message - it defaults to "Fatal error: Program stopped.".

2021-01-04 11:18 UTC, evasseure requested changes

2021-01-04 11:18 UTC, evasseure commented on cprint/cprint.py
> +    def fatal(cls, arg, interrupt=False, fatal_message="Fatal error: Program stopped." *args, **kwargs):
Hello, thanks for the PR!

There's a missing comma tho, so [the tests are failing](https://travis-ci.org/github/EVasseure/cprint).
[![Build Status](https://travis-ci.org/EVasseure/cprint.svg?branch=master)](https://travis-ci.org/EVasseure/cprint)

```suggestion
    def fatal(cls, arg, interrupt=False, fatal_message="Fatal error: Program stopped.", *args, **kwargs):
```

2021-02-05 11:35 UTC, evasseure commented
Thank you for your contribution!

2021-02-05 11:36 UTC, merged

2021-02-05 13:43 UTC, TheTechRobo commented
Any time. :)